apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-download-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-download-app
  uid: dcc971d0-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '9188878'
  generation: 223
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-download-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-download-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-download-app@sha256:0eee5f2f7ba47a2074aa53a4386ff36be6aa65194184f26930e0c86b9192b621
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-download-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-download-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: volume-download
          persistentVolumeClaim:
            claimName: ossim-data-dev-pvc
      containers:
        - name: omar-download-app
          image: >-
            172.30.181.173:5000/o2/omar-download-app@sha256:0eee5f2f7ba47a2074aa53a4386ff36be6aa65194184f26930e0c86b9192b621
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
            - name: BUCKETS
              value: o2-test-data
          resources: {}
          volumeMounts:
            - name: volume-download
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 26
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
            runAsUser: 1001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 207
  observedGeneration: 223
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-download-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T18:15:52Z'
      lastTransitionTime: '2017-10-31T18:15:52Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-12-04T15:32:18Z'
      lastTransitionTime: '2017-12-04T15:32:16Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-download-app-207" successfully rolled out
  readyReplicas: 1
